// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDztLGFLw0Q2ZyD9S2VEO-7A4ZWBcw6Rp4',
    appId: '1:199904881969:web:446c594e4758a52f7bd410',
    messagingSenderId: '199904881969',
    projectId: 'voice-notes-568c5',
    authDomain: 'voice-notes-568c5.firebaseapp.com',
    storageBucket: 'voice-notes-568c5.appspot.com',
    measurementId: 'G-2LYKX4TSX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PpGXNVdjUPzRQWnGLXD3lpqXHsTTaDs',
    appId: '1:199904881969:android:9ef64930a27adb2f7bd410',
    messagingSenderId: '199904881969',
    projectId: 'voice-notes-568c5',
    storageBucket: 'voice-notes-568c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYd1moxdSFz4thL4sQCW-GAjKc9XY54d8',
    appId: '1:199904881969:ios:84ac04c98c3bab427bd410',
    messagingSenderId: '199904881969',
    projectId: 'voice-notes-568c5',
    storageBucket: 'voice-notes-568c5.appspot.com',
    iosBundleId: 'com.example.voiceNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYd1moxdSFz4thL4sQCW-GAjKc9XY54d8',
    appId: '1:199904881969:ios:84ac04c98c3bab427bd410',
    messagingSenderId: '199904881969',
    projectId: 'voice-notes-568c5',
    storageBucket: 'voice-notes-568c5.appspot.com',
    iosBundleId: 'com.example.voiceNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDztLGFLw0Q2ZyD9S2VEO-7A4ZWBcw6Rp4',
    appId: '1:199904881969:web:8576e5333ccda0837bd410',
    messagingSenderId: '199904881969',
    projectId: 'voice-notes-568c5',
    authDomain: 'voice-notes-568c5.firebaseapp.com',
    storageBucket: 'voice-notes-568c5.appspot.com',
    measurementId: 'G-6YR1Z018M0',
  );
}
